version: "3"

services:
  uno-dev:
    build:
      context: .
      dockerfile: fe.dev.Dockerfile
    ports:
      - "8080:80"  # 前端开发服务端口

  uno-server-python-dev:
    build:
      context: ./UNO-server-python
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Python 服务端口
