version: "3"

services:
  uno:
    build:
      context: .
      dockerfile: fe.prod.Dockerfile
    ports:
      - "80:80"  # 前端生产服务端口

  server:
    build:
      context: .
      dockerfile: end.Dockerfile
    ports:
      - "3001:3000"  # 原 Node 服务端口

  uno-server-python:
    build:
      context: ./UNO-server-python
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Python 服务端口
